repos:
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1  # Use the latest revision
    hooks:
      - id: flake8

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0  # Use the latest revision
    hooks:
      - id: isort
        args: ['--profile', 'black']

  - repo: https://github.com/psf/black
    rev: 22.3.0  # Use the latest revision
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0  # Use the latest revision
    hooks:
      - id: mypy
        additional_dependencies: ['types-requests', 'types-pyyaml']
